package org.product.inventory.web.core

object StringRes {

    const val userRoleUser = "user_role_user"
    const val userRoleManager = "user_role_manager"
    const val userRoleAdministrator = "user_role_administrator"

    const val authTextWelcome = "auth_text_welcome"
    const val authTextContinue = "auth_text_continue"
    const val authTextLogin1 = "auth_text_login1"
    const val authTextLogin2 = "auth_text_login2"
    const val authMessageSuccessTitle = "auth_message_success_title"
    const val authMessageSuccessDescription = "auth_message_success_description"
    const val authMessageWarningTitle = "auth_message_warning_title"
    const val authMessageWarningDescription = "auth_message_warning_description"
    const val authMessageErrorTitle = "auth_message_error_title"
    const val authMessageErrorDescription = "auth_message_error_description"

    const val menuTestDevices = "menu_test_devices"
    const val menuParkingReservation = "menu_parking_reservation"
    const val menuSeatReservation = "menu_seat_reservation"
    const val menuLogout = "menu_logout"

    const val parkingReservationTitle = "parking_reservation_title"
    const val parkingReservationPath1 = "parking_reservation_pat1"
    const val parkingReservationPath2 = "parking_reservation_path2"
    const val reservationItemNewRequestTitle = "reservation_item_new_request_title"
    const val reservationItemNewRequestDescription = "reservation_item_new_request_description"
    const val reservationItemUserRequestsTitle = "reservation_item_user_requests_title"
    const val reservationItemUserRequestsDescription = "reservation_item_user_requests_description"
    const val reservationItemCrewManagementTitle = "reservation_item_crew_management_title"
    const val reservationItemCrewManagementDescription =
        "reservation_item_crew_management_description"
    const val reservationItemMyReservationsTitle = "reservation_item_my_reservations_title"
    const val reservationItemMyReservationsDescription =
        "reservation_item_my_reservations_description"
    const val reservationItemEmailTemplatesTitle = "reservation_item_email_templates_title"
    const val reservationItemEmailTemplatesDescription =
        "reservation_item_email_templates_description"
    const val reservationItemSlotsManagementTitle = "reservation_item_slots_management_title"
    const val reservationItemSlotsManagementDescription =
        "reservation_item_slots_management_description"

    const val newRequestTitle = "new_request_title"
    const val newRequestPath1 = "new_request_path1"
    const val newRequestPath2 = "new_request_path2"
    const val newRequestPath3 = "new_request_path3"
    const val newRequestLateReservationMessage = "new_request_late_reservation_message"
    const val parkingReservationNewRequestAs = "parking_reservation_new_request_as"
    const val parkingReservationNewRequestDate = "parking_reservation_new_request_date"
    const val parkingReservationNewRequestAdditionalNotes =
        "parking_reservation_new_request_additional_notes"
    const val parkingReservationNewRequestAdditionalNotesPlaceholder =
        "parking_reservation_new_request_additional_notes_placeholder"
    const val parkingReservationNewRequestSubmit = "parking_reservation_new_request_submit"
    const val parkingReservationNewRequestAddDate = "parking_reservation_new_request_add_date"
    const val parkingReservationDuplicateReservationError = "parking_reservation_duplicate_reservation_error"
    const val parkingReservationLateReservationError = "parking_reservation_late_reservation_error"
    const val parkingReservationNewRequestEmptyUserListMessage = "parking_reservation_new_request_empty_user_list_message"
    const val parkingReservationNewRequestFilterPlaceholder = "parking_reservation_new_request_filter_placeholder"
    const val parkingReservationNewRequestUserListErrorMessage = "parking_reservation_new_request_user_list_error_message"
    const val parkingReservationDuplicateRequestErrorMessage = "parking_reservation_duplicate_request_error_message"
    const val parkingReservationTooManyRequestsErrorMessage = "parking_reservation_too_many_requests_error_message"

    const val myReservationsTitle = "my_reservations_title"
    const val parkingReservationItemFrom = "parking_reservation_item_from"
    const val parkingReservationItemTo = "parking_reservation_item_to"
    const val myReservationsPath1 = "my_reservations_path1"
    const val myReservationsPath2 = "my_reservations_path2"
    const val myReservationsPath3 = "my_reservations_path3"
    const val myParkingReservationSubmitted = "my_reservations_submitted_date_label"
    const val myParkingReservationCancelRequest = "my_parking_reservation_cancel_request"
    const val parkingReservationItemRequestedDate = "parking_reservation_item_requested_date"
    const val parkingReservationItemNote = "parking_reservation_item_note"
    const val parkingReservationItemDate = "parking_reservation_item_date"
    const val myParkingReservationEmpty = "my_reservations_empty_list_message"
    const val myReservationsCancelReservationDialogMessage = "my_reservations_cancel_reservation_dialog_message"
    const val myReservationsCancelReservationDialogPositiveText = "my_reservations_cancel_reservation_dialog_positive_text"
    const val myReservationsCancelReservationDialogNegativeText = "my_reservations_cancel_reservation_dialog_negative_text"

    const val parkingReservationUserRequestSave = "parking_reservation_user_request_save"

    const val parkingReservationRetryScreenTitle = "parking_reservation_retry_screen_title"
    const val parkingReservationRetryScreenDescription =
        "parking_reservation_retry_screen_description"
    const val parkingReservationRetryScreenButtonText =
        "parking_reservation_retry_screen_button_text"

    const val parkingReservationItemGarageLevel = "parking_reservation_item_garage_level"
    const val parkingReservationItemParkingSpot = "parking_reservation_item_parking_spot"
    const val parkingReservationItemRequestedBy = "parking_reservation_item_requested_by"
    const val parkingReservationItemAdditionalNotes = "parking_reservation_item_additional_notes"
    const val parkingReservationItemApproveNote = "parking_reservation_item_approve_note"
    const val parkingReservationItemRejectReason = "parking_reservation_item_reject_reason"

    const val parkingReservationStatusApprovedLabel = "parking_reservation_status_approved_label"
    const val parkingReservationStatusCanceledLabel = "parking_reservation_status_canceled_label"
    const val parkingReservationStatusRejectedLabel = "parking_reservation_status_rejected_label"
    const val parkingReservationStatusSubmittedLabel = "parking_reservation_status_submitted_label"

    const val userRequestsTitle = "user_requests_title"
    const val userRequestsPath1 = "user_requests_path1"
    const val userRequestsPath2 = "user_requests_path2"
    const val userRequestsPath3 = "user_requests_path3"
    const val userRequestsEmailLabel = "user_requests_email_label"
    const val userRequestsSubmittedDateLabel = "user_requests_submitted_date_label"
    const val userRequestsRequestedDateLabel = "user_requests_requested_date_label"
    const val userRequestsAdminNotesLabel = "user_requests_admin_notes_label"
    const val userRequestsAdminAdditionalNotes = "user_requests_admin_additional_notes"
    const val userRequestsApproveNoteLabel = "user_requests_approve_note_label"
    const val userRequestsGarageLevelLabel = "user_requests_garage_level_label"
    const val userRequestsParkingSpotLabel = "user_requests_parking_spot_label"
    const val userRequestsSaveButtonText = "user_requests_save_button_text"
    const val userRequestsRejectReasonLabel = "user_requests_reject_reason_label"
    const val userRequestsParkingErrorMessage = "user_requests_parking_error_message"
    const val userRequestsParkingErrorMessageRetry = "user_requests_parking_error_message_retry"
    const val userRequestsNoParkingSpacesMessage = "user_requests_no_parking_spaces_message"
    const val userRequestsGarageAccessLabel = "user_requests_garage_access_label"
    const val userRequestsUserEmailFilterPlaceholder = "user_requests_user_email_filter_placeholder"
    const val userRequestsUserEmailFilterLabel = "user_requests_user_email_filter_label"
    const val userRequestsStatusFilterAllOptionText = "user_requests_status_filter_all_option_text"

    const val crewManagementTitle = "crew_management_title"
    const val crewManagementPath1 = "crew_management_path1"
    const val crewManagementPath2 = "crew_management_path2"
    const val crewManagementRegisteredUsersLabel = "crew_management_registered_users_label"
    const val crewManagementAddButtonText = "crew_management_add_button_text"
    const val crewManagementSaveButtonText = "crew_management_save_button_text"
    const val crewManagementEmailLabel = "crew_management_email_label"
    const val crewManagementRoleLabel = "crew_management_role_label"
    const val crewManagementHasPermanentGarageAccessLabel = "crew_management_has_permanent_garage_access_label"
    const val crewManagementRequestAddUserSuccess = "crew_management_request_add_user_success"
    const val crewManagementRequestEditUserSuccess = "crew_management_request_edit_user_success"
    const val crewManagementInvalidEmailErrorMessage = "crew_management_invalid_email_error_message"
    const val crewManagementDuplicatedEmailErrorMessage = "crew_management_duplicated_email_error_message"

    const val slotsManagementTitle = "slots_management_title"
    const val slotsManagementPath1 = "slots_management_path1"
    const val slotsManagementPath2 = "slots_management_path2"
    const val slotsManagementPath3 = "slots_management_path3"
    const val slotsManagementLevelLabel = "slots_management_level_label"
    const val slotsManagementRegisteredSpotsLabel = "slots_management_registered_spots_label"
    const val slotsManagementNewGarageLevelLabel = "slots_management_new_garage_level_label"
    const val slotsManagementPopupOptionEdit = "slots_management_popup_option_edit"
    const val slotsManagementPopupOptionDelete = "slots_management_popup_option_delete"
    const val slotsManagementSpotLabel = "slots_management_spot_label"
    const val slotsManagementRequestAddSuccess = "slots_management_request_add_success"
    const val slotsManagementRequestEditSuccess = "slots_management_request_edit_success"
    const val slotsManagementRequestFailure = "slots_management_request_failed"
    const val slotsManagementRequestDeleteSuccess = "slots_management_request_delete_success"
    const val slotsManagementRequestDeleteFailure = "slots_management_request_delete_failure"
    const val slotsManagementDeleteGarageLevelDialogTitle = "slots_management_delete_garage_level_dialog_title"
    const val slotsManagementDeleteGarageLevelDialogMessage = "slots_management_delete_garage_level_dialog_message"
    const val slotsManagementDeleteGarageLevelDialogPositiveText = "slots_management_delete_garage_level_dialog_positive_text"
    const val slotsManagementDeleteGarageLevelDialogNegativeText = "slots_management_delete_garage_level_dialog_negative_text"
    const val slotsManagementDetailsTitleLabel = "slots_management_details_title_label"
    const val slotsManagementDetailsTitlePlaceholder = "slots_management_details_title_placeholder"
    const val slotsManagementDetailsSpotsLabel = "slots_management_details_spots_label"
    const val slotsManagementDetailsNewSpotNamePlaceholder = "slots_management_details_new_spot_name_placeholder"
    const val slotsManagementDetailsSaveButtonText = "slots_management_details_save_button_text"

    const val emailTemplatesTitle = "email_templates_title"
    const val emailTemplatesPath1 = "email_templates_path1"
    const val emailTemplatesPath2 = "email_templates_path2"
    const val emailTemplatesPath3 = "email_templates_path3"
    const val emailTemplatesSaveButtonText = "email_templates_save_button_text"
    const val emailTemplatesCloseButtonText = "email_templates_close_button_text"
    const val emailTemplatesEmptyListMessage = "email_templates_empty_list_message"
    const val emailTemplatesFetchErrorMessage = "email_templates_fetch_error_message"
    const val emailTemplatesRequestEditSuccess = "email_templates_request_edit_success"
    const val emailTemplatesRequestEditFailure = "email_templates_request_edit_failure"

    const val seatReservationTitle = "seat_reservation_title"
    const val seatReservationPath1 = "seat_reservation_path1"
    const val seatReservationPath2 = "seat_reservation_path2"
    const val seatReservationSeatManagementTitle = "seat_reservation_seat_management_title"
    const val seatReservationSeatManagementDescription = "seat_reservation_seat_management_description"
    const val seatReservationTimelineTitle = "seat_reservation_timeline_title"
    const val seatReservationTimelineDescription = "seat_reservation_timeline_description"

    const val seatReservationManagementTitle = "seat_reservation_management_title"
    const val seatReservationManagementPath1 = "seat_reservation_management_path1"
    const val seatReservationManagementPath2 = "seat_reservation_management_path2"
    const val seatReservationManagementAddOfficeSuccess = "seat_reservation_management_add_office_success"
    const val seatReservationManagementAddOfficeError = "seat_reservation_management_add_office_error"
    const val seatReservationManagementDeleteOfficeSuccess = "seat_reservation_management_delete_office_success"
    const val seatReservationManagementDeleteOfficeError = "seat_reservation_management_delete_office_error"
    const val seatReservationManagementEditOfficeSuccess = "seat_reservation_management_edit_office_success"
    const val seatReservationManagementEditOfficeError = "seat_reservation_management_edit_office_error"
    const val seatReservationManagementNewOfficeNamePlaceholder = "seat_reservation_management_new_office_name_placeholder"
    const val seatReservationManagementOfficeLabel = "seat_reservation_management_office_label"
    const val seatReservationManagementNumberOfSeatsLabel = "seat_reservation_management_number_of_seats_label"
    const val seatReservationManagementPopupOptionEdit = "seat_reservation_management_popup_option_edit"
    const val seatReservationManagementPopupOptionDelete = "seat_reservation_management_popup_option_delete"
    const val seatReservationManagementDeleteDialogTitle = "seat_reservation_management_delete_dialog_title"
    const val seatReservationManagementDeleteDialogMessage = "seat_reservation_management_delete_dialog_message"
    const val seatReservationManagementDeleteDialogPositiveText = "seat_reservation_management_delete_dialog_positive_text"
    const val seatReservationManagementDeleteDialogNegativeText = "seat_reservation_management_delete_dialog_negative_text"
    const val seatReservationManagementEditDialogTitle = "seat_reservation_management_edit_dialog_title"
    const val seatReservationManagementEditDialogNameLabel = "seat_reservation_management_edit_dialog_name_label"
    const val seatReservationManagementEditDialogNumberOfSeatsLabel = "seat_reservation_management_edit_dialog_number_of_seats_label"
    const val seatReservationManagementEditDialogButtonText = "seat_reservation_management_edit_dialog_button_text"
    const val seatReservationManagementEditDialogNamePlaceholder = "seat_reservation_management_edit_dialog_name_placeholder"
    const val seatReservationManagementOfficeNameExistsError = "seat_reservation_management_office_name_exists_error"

    const val seatReservationTimelinePageTitle = "seat_reservation_timeline_page_title"
    const val seatReservationTimelinePath1 = "seat_reservation_timeline_path1"
    const val seatReservationTimelinePath2 = "seat_reservation_timeline_path2"
    const val seatReservationTimelineReserveButtonText = "seat_reservation_timeline_reserve_button_text"
    const val seatReservationTimelineCancelButtonText = "seat_reservation_timeline_cancel_button_text"
    const val seatReservationTimelineWeekendButtonText = "seat_reservation_timeline_weekend_button_text"
    const val seatReservationTimelineSeatsReaminingText = "seat_reservation_timeline_seats_reaming_text"
    const val seatReservationTimelineReserveSeatFailureText = "seat_reservation_timeline_reserve_seat_failure_text"
    const val seatReservationTimelineCancelSeatFailureText = "seat_reservation_timeline_cancel_seat_failure_text"

    const val alertMessageSuccess = "parking_reservation_success"
    const val alertMessageFailure = "parking_reservation_failure"

    const val emailReservationUpdatedTItle = "email_title"
}
